### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-api-contracts#34]
Currently the README.md is missing some of the links of the API contracts. There are more folders (contracts) than there are number of links/titles in the README

The ones marked in red are missing from the main README.md of this repo:
![image](https://user-images.githubusercontent.com/56217868/109763759-8eb1ac00-7c18-11eb-88b0-02fd789489cb.png)

We need to add those missing links in the README.md

**Comment by swarajpure** [comment]
Also, it would be better if the titles in the **main** README are arranged in the same order and they appear in the folder structure

For example:
`Contributions` should be at the top
`Users` should be at the bottom

**Comment by swarajpure** [comment]
This documentation will help you 🙂 
https://github.com/Real-Dev-Squad/website-welcome/blob/main/CONTRIBUTING.md

**Comment by iRahulP** [comment]
@swarajpure  ,Can I start working on this issue as I can also get the gist of submitting my first PR.
