### ISSUE TITLE
Add new task status in Task object documentation

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-api-contracts#55]
Add `unAssigned` status in `task` object
[Discord discussion](https://discord.com/channels/673083527624916993/735063616168001536/848892753004986369)
[Task object to be changed](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/tasks)

**Comment by KhushalAbrol** [comment]
Assign me this task plz

**Comment by KhushalAbrol** [comment]
Please review the pull request

**Comment by KhushalAbrol** [comment]
https://github.com/Real-Dev-Squad/website-api-contracts/pull/56
