### ISSUE TITLE
API contract to GET /tasks (with query)

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-api-contracts#83]
This is to extend the ability of the ```GET /tasks ``` API from the backend to also support filtering by parameters passed as queries.
The functioning would be as follows:-

1. If no query parameters passed i.e `limit or offset` then the response will get all the tasks there are in the database or default to a no. of documents to return.
2. If query parameters `limit and offset` is passed then it would return all the documents which are created after the created time of the <task_object> whose `id = offset`, plus would only return `n` no. of documents where `n = limit` and therefore would also work as a paginated API.

**Comment by prakashchoudhary07** [comment]
Closing this as the PR linked to this issue has been closed, as the API contracts are outdated, and new API contracts have been updated
